spring:
  application:
    name: grinder
  datasource:
    driver-class-name: ENC(YtATyRWSL8SyRCJU8G0ZKFzKAMQANWkAddPGwfFoU1DRUgg0fE66gQ==)
    url: ENC(yo7JTw++2Ds7Zjpc/XXCN1r7/sSqhh+5wYyRZN0orvn0/zDfYry+n62FZvuO4wxuSlgpr56ut1N/lIYCZIfVucjZXyLo1FiyZgX2hnFZYOraUz+fLHrPfNoC0DKU2+tR2Yy1NS9/aCBN0vKouv9TNStYwaboY1EZZPtLDGBGj8kpz04qqJHc2Q==)
    username: ENC(eE3mUyVOsUjwd9yYtjVpVPag5rA35b3X)
    password: ENC(VKJKmbAUaTjqcPeQSO4mTmPfpZVEQxtc)
    hikari:
      connection-timeout: 10000
      minimum-idle: 3
      maximum-pool-size: 6
      idle-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ENC(A01rFFFrdjnrXPLUVRfUPaLTuEh/7CNQMnmz2k+I+Do=)
            client-secret: ENC(QEiT7wBx0jf/g1xSUNbm2qy1wddmi+YG)
            redirect-uri: ENC(0FjbdFd48fGTRYmIhhx3ECbnU/mXXdnzlphaJPkdmFhCS1ZHj+uukRrYQNw9hBUaduqWrYpNsqI=)
            authorization-grant-type: authorization_code
            provider: naver
            scope:
              - name
              - email
          google:
            client-name: google
            client-id: ENC(V490RKXNhE/ALCThvQ8mn2ug5iAPEBslVtmyf+Nj2e/4BjUi/nMFF28SK03XmGLA2+Uk9H7VdH09FTT/MfZ5QBRn6MJmXnyZ5dUcIKZvSA2jshPEt65wOg==)
            client-secret: ENC(nGqYf4lXEMug9H3L7g43SeUrc/dZPbGi1F6tpeSk+xYLJZdgZO3W6XxCCvOt1rtp)
            redirect-uri: ENC(ASp7UJmaek2dq0pemsnxQZqGg/1QDibwfeizap9cq4YOO2sYagjHc3d1rnHaf7fx3Y/Obx//K78=)
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          kakao:
            client-name: kakao
            client-id: ENC(SduSAns6b7+t6z2aUEwgFtGa55HV/Sg/Zjx88kxflmXJZtp3cfSxDWthJ2IdGqb2s1g7DZ2ugmVDIVSdBd/pWrCQcwxS1HbNYalbLUHhP1JC9wvve3QXpA==)
            client-secret: ENC(3BAeFwz8gx79HgwJjt+ps7IjTl0c4TwRW4eLJdSeN5JQj3DQbseC1ydsnXPATFnI)
            redirect-uri: ENC(6Qmq2YAE4wXHnL4OcJnAOf7+aeFyH581qQHbiRgMwD5pEu6S1K3n4Q3dzkRZ5wcE)
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            provider: kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: ENC(L3TUfDftVcZF1axe/TLFuToCtuxL/eljmkkWSjKZjUtZjtLhP0QXIVECgqDaTW66ExvEQ6FZlLY=)
            token-uri: ENC(jd4pV2o0QRrm/foJLI2ZAIvkw1Da07WU/YThyQj2xDXON8BfK3+ZO+SpgOWJlmth)
            user-info-uri: ENC(bGgsB5BfKxx1wfld1uowiqxH+g5e1BYpTZ+Jg42p+QfkrGTSNAqAOnofczUMKRMW)
            user-name-attribute: response
          kakao:
            authorization-uri: ENC(EunSJKAo+dBdPkTdeiCftstTwC1iEEFoz10SWEPwTSiSS4jARcp6+DNPvizYsC1Y)
            token-uri: ENC(kVlGej8uAR+UDgdu7Ww/yShrSJW+S6zsZ950oq5lbZ7sdtAgZEIehMo+/m0BCwxO)
            user-info-uri: ENC(3yUw4QqZw04bKHuQXHdJV6VwlvECpwAPxuIHUX7usRH8SUZNntnXe9w9RKxjeLFo)
            user-name-attribute: id
  # devtools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

server:
  tomcat:
    threads:
      min-spare: 2
      max: 5

logging:
  level:
    org:
      springframework:
        info:
        security: trace
    zercok: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"

# AWS amazon S3
cloud:
  aws:
    credentials:
      access-key: ENC(U3mPaYT6Vb27V0MA7ldZ8SuE7Gomzz4QNv/bjW+6STs=)
      secret-key: ENC(+STVVOAGWuwv+zVPN2H2PEjs2cPFWtaDUkRf5TuKdKMzxLunl+meySz7al0J8PVH8f0A8dp2rrQ=)
    region:
      static: ap-northeast-2
    stack:
      auto: false

jasypt:
  encryptor:
    bean: jasyptStringEncryptor