spring:
  application:
    name: grinder
  datasource:
    driver-class-name: ENC(8LpmAiJQECOI11AxFKX4Yy1L4hhe6INfzPX6IZLJ9+pXVP0rXXzItg==)
    url: ENC(XXBgWVUMkX4nTq57MSv4UQ6audCNWoxyYyAEN2eItzsXd6kc2xhx+fVBIT04fCYLiOS4ThhstOCsO4E1KMsSC3tNS6FydckUbbCA3Zcpji8x9JFay0Z+zdVD/9AyT+lrhUnpX8Nc5CuOrSqAfeeuy964/c5VckNK/VsV/aE5R5JOSij+2XVnkQ==)
    username: ENC(v2AaujIJS6TKNBGTe9ytq7sN95ARDkXl)
    password: ENC(+Php42aNrf6Grd5REAMwxoawZbbt9c1B)
    hikari:
      connection-timeout: 10000
      minimum-idle: 3
      maximum-pool-size: 6
      idle-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ENC(xs433lqcQEnLCDKQzqUl1UxfZ7IvSIeMCLqwhFltoo8=)
            client-secret: ENC(L9lfZ7fjKh2P8yGBgp0Dl9zfijdLTnfe)
            redirect-uri: ENC(Nj0RBtY+xqVISajDs1IX4zh6P0cVPWwF6398iyViknm7ZSuqa0nNeth73advTfal2x2/kJ0XRCA=)
            authorization-grant-type: authorization_code
            provider: naver
            scope:
              - name
              - email
          google:
            client-name: google
            client-id: ENC(1XDmsnvdsrUeSDhc2yxrguZaiuOqPCM9PztxtVp5pAGb4e17HVVIUPPC3hkhIHCBVOe6X3L7ICxfmI+hDZkrcI5lzRUL/ZE6aA25o/kMP5+GdiM7nJq2Ug==)
            client-secret: ENC(RhxiCRc5b4IoWMBAxdgyxt5mNOAHf+N7ZcBA0vUQaXMlFRFfcrT8By45A3tAnQ+y)
            redirect-uri: ENC(UNt+Qptpr1jQjaUTaHWvTezWPCRph0iTjEg1Frs5/oP5WqAGn+CvqBBMUCD6hQJA+H1zXKTZem4=)
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          kakao:
            client-name: kakao
            client-id: ENC(5zVb4WM/7L1mdo0VIM9O2hNuTL8InqO8ZyftCN/ifYFAKLiJKzAKHPUTDrGaEazr)
            client-secret: ENC(hdh3y0+faeC87jhUpqxgbWNVRwxFSWYcg8sEqv6Gftlcc+2zG2jjTpPWZ/AB2CH5)
            redirect-uri: ENC(HZ3b/tWDAgpAEQb3duhJjpHCubJtbCUYKFKN/fHPPFAkutJp4fwvceJoqkeA5ZXWtNn7P35W5oo=)
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            provider: kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: ENC(JAAReGYO7Q7afgsmiVnMNg49JrEO9EwFLo7B8diFFYNxKCrspsK6oIhwS9AqUu+TTrWpChDU28Q=)
            token-uri: ENC(o1gUiK8z7ZIUPA9jlqZ8UkeVwVGMqiKOWrPpCzMX04UgAu5cXCbazldaISIayxc6)
            user-info-uri: ENC(G6Cwtgg/+V2oP0z7KR3g8odw33B2NxIXmt9sKUDWDWFl+H1pjr6m5UytxCND+YNm)
            user-name-attribute: response
          kakao:
            authorization-uri: ENC(IC+HGAH0U7CwGjUSkmrqTaUssAK/yq9hLPhN1T2gYMzAS935cfK7bWIF/57WlVdL)
            token-uri: ENC(I4IXLOj1PtZ/JdjftPxoeWk4MWGhWPgmoj2CWyOWHHbQRkAMU31AViETNfLpK03H)
            user-info-uri: ENC(tt/0kAgwfU+oWBwJ+DFIIMdM4hMFU06PI/oS8pLq13F5GXTUC3TPFN9EceLPF9um)
            user-name-attribute: id
  # devtools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

server:
  tomcat:
    threads:
      min-spare: 2
      max: 5

logging:
  level:
    org:
      springframework:
        info:
        security: trace
    zercok: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"

# AWS amazon S3
cloud:
  aws:
    credentials:
      access-key: ENC(c/nl1ht6EBleynVjvw2BF1Pgu3gf71dLHxi3gUYBrfE=)
      secret-key: ENC(zKIpk2OsKXWjmm24p3Ii7JEAxHcOHgVyDJOGIlJN3Ir7dgooWToFgBZGCfJaL5AtDXbnByxKtXQ=)
    region:
      static: ap-northeast-2
    stack:
      auto: false

jasypt:
  encryptor:
    bean: jasyptStringEncryptor